# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias home='cd ~ && echo Welcome home'
alias gin='git init'
alias ga='git add'
alias gst='git status'
alias gl='git log'
alias cls='clear'
alias gmain='git push origin main'
alias gp='git push'
alias gremote='git remote -v'

grmtadd() {
    git remote add "S1" "S2"
}

gcmess() {
    git commit -m "S1"
}

alias gempty='git commit --allow-empty-message'
