code --install-extension adpyke.codesnap
code --install-extension angular.ng-template
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension catppuccin.catppuccin-vsc
code --install-extension csharpier.csharpier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension devsense.composer-php-vscode
code --install-extension devsense.intelli-php-vscode
code --install-extension devsense.phptools-vscode
code --install-extension devsense.profiler-php-vscode
code --install-extension donjayamanne.githistory
code --install-extension eamodio.gitlens
code --install-extension editorconfig.editorconfig
code --install-extension enkia.tokyo-night
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension github.copilot
code --install-extension github.copilot-chat
code --install-extension github.remotehub
code --install-extension github.vscode-github-actions
code --install-extension inferrinizzard.prettier-sql-vscode
code --install-extension mathematic.vscode-pdf
code --install-extension ms-dotnettools.csdevkit
code --install-extension ms-dotnettools.csharp
code --install-extension ms-dotnettools.vscode-dotnet-runtime
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-vscode-remote.remote-wsl
code --install-extension ms-vscode.azure-repos
code --install-extension ms-vscode.powershell
code --install-extension ms-vscode.remote-repositories
code --install-extension n3rds-inc.pomodoro-timer-focus
code --install-extension pkief.material-icon-theme
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.liveserver
code --install-extension shalldie.background
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shopify.ruby-lsp
code --install-extension tonybaloney.vscode-pets
code --install-extension unthrottled.doki-theme
code --install-extension vintharas.learn-vim
code --install-extension vmware.vscode-boot-dev-pack
code --install-extension vmware.vscode-spring-boot
code --install-extension vscjava.migrate-java-to-azure
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-java-upgrade
code --install-extension vscjava.vscode-maven
code --install-extension vscjava.vscode-spring-boot-dashboard
code --install-extension vscjava.vscode-spring-initializr
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vue.volar
code --install-extension wenyikun.dodo-reader
code --install-extension xdebug.php-debug
code --install-extension xdebug.php-pack
code --install-extension zobo.php-intellisense
