# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

alias home='cd ~ && echo Welcome home!'
alias gin='git init'
alias ga='git add'
alias gst='git status'
alias gl='git log'
alias cls='clear'
alias gpmain='git push origin main'
alias gremote='git remote -v'
alias bye='echo Bye! && exit'

gpup() {
  # Lấy tên nhánh hiện tại
  current_branch=$(git rev-parse --abbrev-ref HEAD)

  # Kiểm tra có commit chưa
  if [ -z "$(git status --porcelain)" ]; then
    echo "✅ Nothing to commit. Pushing branch '$current_branch'..."
  else
    echo "⚠️ You have uncommitted changes. Please commit first!"
    return 1
  fi

  # Đẩy code lên remote origin với nhánh hiện tại
  git push origin "$current_branch"
}

alias gempty='git commit --allow-empty-message'
